name: Sync Fork on Dispatch

on:
  repository_dispatch:
    types: [sync-upstream]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the fork
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/TripGenius/tripgenius-frontend.git
          git fetch upstream
          git checkout main
          git reset --hard upstream/main
          git push origin main --force

